# Generated by Django 3.0.7 on 2020-09-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200922_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_slide',
            field=models.BooleanField(default=False),
        ),
    ]
